languageCode: "en-gb"
title: "ainsley.dev"
theme: "ainsley.dev"
enableRobotsTXT: true
params:
  title: Title of the site
  description: Description of the site
  images:
    - images/site-feature-image.jpg
googleAnalytics: UA-PROPERTY_ID
disableKinds: ["taxonomy", "taxonomyTerm"]
ignoreErrors: ["error-disable-taxonomy"]
sitemap:
    changefreq: monthly
    filename: sitemap.xml
    priority: 0.5
markup:
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
module:
    mounts:
        - source: "./themes/reddico/node_modules/vanilla-lazyload/dist/lazyload.js"
          target: "assets/js/lazyload.js"
