languageCode: en-gb
title: ainsley.dev® - Digital Craftsmanship Sculpting You As An Industry Leader.
baseUrl: "http://localhost:1313"
build:
    noJSConfigInAssets: true
    writeStats: true
disableKinds: [ "taxonomy", "taxonomyTerm" ]
ignoreErrors: [ "error-disable-taxonomy" ]
copyright: "ainsley.dev LTD is a registered company in England and Wales. Company Number 12478393. ©2022 ainsley.dev LTD. All rights reserved."
disableHugoGeneratorInject: true
enableGitInfo: false
enableEmoji: true
enableInlineShortcodes: true
enableRobotsTXT: true
imaging:
    hint: photo
    quality: 75
    resampleFilter: Lanczos
module:
    mounts:
        -   source: "assets"
            target: "assets"
        -   source: "static"
            target: "assets"
markup:
    defaultMarkdownHandler: goldmark
    goldmark:
        extensions:
            definitionList: true
            footnote: true
            linkify: true
            linkifyProtocol: https
            strikethrough: true
            table: true
            taskList: true
            typographer: true
        parser:
            attribute:
                block: true
                title: true
            autoHeadingID: true
            autoHeadingIDType: github
            wrapStandAloneImageWithinParagraph: false
        renderer:
            hardWraps: false
            unsafe: true
            xhtml: false
    highlight:
        codeFences: true
        lineNos: true
        lineNumbersInTable: false
        noClasses: false
        noHl: false
        tabWidth: 4
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
outputs:
    home: ["HTML","RSS", "JSON"]
    section: ["HTML","RSS", "JSON"]
security:
    exec:
        allow: [ "^dart-sass-embedded$", "^go$", "npx$", "^postcss$", "^babel$" ]
sitemap:
    changefreq: monthly
    filename: sitemap.xml
    priority: 0.5


