languageCode: "en-gb"
title: "ainsley.dev"
theme: "ainsley.dev"
build:
    writeStats: true
disableKinds: [ "taxonomy", "taxonomyTerm" ]
ignoreErrors: [ "error-disable-taxonomy" ]
copyright: "ainsley.dev LTD is a registered company in England and Wales. Company Number 12478393. ©2022 ainsley.dev LTD. All rights reserved."
disableHugoGeneratorInject: true
enableGitInfo: true
enableEmoji: true
enableInlineShortcodes: true
enableRobotsTXT: true
googleAnalytics: UA-PROPERTY_ID
imaging:
    hint: photo
    quality: 75
    resampleFilter: Lanczos
module:
    mounts:
        -   source: "./themes/reddico/node_modules/vanilla-lazyload/dist/lazyload.js"
            target: "assets/js/lazyload.js"
markup:
    defaultMarkdownHandler: goldmark
    goldmark:
        extensions:
            definitionList: true
            footnote: true
            linkify: true
            linkifyProtocol: https
            strikethrough: true
            table: true
            taskList: true
            typographer: true
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
security:
    exec:
        allow:  ["^dart-sass-embedded$", "^go$", "npx$", "^postcss$", "^babel$"]
sitemap:
    changefreq: monthly
    filename: sitemap.xml
    priority: 0.5
