description: Digital craftsmanship sculpting you as an industry leader. Coupling state-of-the-art technology with beautiful, memorable designs, we create memorable digital transformations and well-crafted software for everyone from startups to established brands.
images:
    - images/site-feature-image.jpg
logo: change
company:
    name: ainsley.dev LTD
    number: 14550437
contact:
    email: "hello@ainsley.dev"
    address: ainsley.dev, 71-75 Shelton Street, Covent Garden, London, WC2H 9JQ
    locality: change
    country: change
    postalCode: change
    map: "https://www.google.com/maps/place/ainsley.dev/@51.5139491,-0.1232573,17.02z/data=!4m6!3m5!1s0x487605b625a28957:0xa6030818dec3f050!8m2!3d51.5149037!4d-0.1235842!16s%2Fg%2F11shgfsthh"
    phone:
        link: +447507784206
        pretty: +44 7507 784 206
social:
    github: "https://github.com/ainsleyclark"
    linkedin: "https://www.linkedin.com/in/ainsleyclark/"
    twitter: "https://twitter.com/ainsleydev/"
    facebook: "https://www.facebook.com/ainsley.devltd/"
    instagram: "https://www.instagram.com/ainsley.devltd/"
    dribbble: "https://dribbble.com/ainsleyclark/"
imagery:
    webpAvif: false
    container:
        -   name: mob
            size: 768
        -   name: tab
            size: 1024
