name: Can I Deploy

on:
    workflow_dispatch:
    pull_request:
        branches: [ master ]

jobs:
    build:
        name: Release & Deploy
        runs-on: ubuntu-latest
        strategy:
            matrix:
                go-version: [ 1.19.x ]
        steps:
            # Step 1 - Checks-out your repository under $GITHUB_WORKSPACE
            -   name: Checkout
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            # Step 2 - Install Go on the runner
            -   name: Install Go
                uses: actions/setup-go@v3
                with:
                    go-version: ${{ matrix.go-version }}

            # Step 4 - Build
            -   name: Build
                run: make setup
