name: Lint Typescript

on:
    workflow_dispatch:
    pull_request:
        branches: [ master ]

jobs:
    test:
        name: Lint Typescript
        runs-on: ubuntu-latest
        strategy:
            matrix:
                go-version: [ 1.19.x ]
        steps:
            # Step 1 - Checks-out your repository under $GITHUB_WORKSPACE
            -   name: Checkout
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0
                run: npm install

            # Step 2 - Run ESLint
            -   name: Lint
                run: npm run lint:js
